### PR TITLE
Add contributors section

### PR DESCRIPTION
**Pull request by rishabh3112**
in `package.json`

### CODE REVIEW

**Comment by sendilkumarn** [comment]
I am sorry, I haven't seen this. Can we not have this, please? 

It will bloat the `package.json` and it will be an unnecessary overhead at every commit and I don't want this. 

Can we close this ?

**Comment by rishabh3112** [comment]
Sure
Well there is an awesome package at [npm](https://www.npmjs.com/package/contributor) if you want to use else where

**Comment by sendilkumarn** [comment]
@rishabh3112 I really don't want that, may be we can add a new webpage for that here (WDYT) if you really really want it

**Comment by rishabh3112** [comment]
Ohh dear @sendilkumarn 🤦‍♂️  
I was just referring to the package for you only
**I Have no problem in dumping this PR**

**Comment by rishabh3112** [comment]
Webpage will be fine but after we have released v1.0.0 and when extensive documentation is required.
I think we should **focus** on development first.

**Pull request closed without merging**
