### PR TITLE
migrate(typescript): [WIP] Shifting codebase to Typescript

### PR DESCRIPTION
**Pull request by rishabh3112**
Migrating whole plugin to `.ts` ✌

### CODE REVIEW

**Comment by rishabh3112** [comment]
Waiting for webpack/webpack-cli#577 and webpack/webpack-cli#577 to resolve which will certainly solve the remaining errors rest work done 😉✌

**Comment by rishabh3112** [comment]
The scaffold isn't working as of now so don't merge it @sendilkumarn
error encountered is sent on Slack

**Comment by sendilkumarn** [comment]
@rishabh3112 Do you still have the error?

**Comment by sendilkumarn** [comment]
There is a merge conflict, can you fix it?

> The entry point will be in JavaScript

Is it because of yeoman?

**Comment by rishabh3112** [comment]
> There is a merge conflict, can you fix it?
Would be able to do within 3-4 days as I have my laptop shut right now.
If you are free it would be awesome!!

> Is it because of yeoman?
Checkout slack

**Comment by sendilkumarn** [comment]
closing in favor of #63

**Pull request closed without merging**
