### PR TITLE
Feature/webpack config

### PR DESCRIPTION
**Pull request by AjayPoshak**
It will resolve [#35](https://github.com/sendilkumarn/webpack-scaffold-pwa/issues/35)

### CODE REVIEW

**Comment by sendilkumarn** [comment]
This is great, but wondering whether the `webpack-cli` has this already?

**Comment by AjayPoshak** [comment]
@sendilkumarn I don't get it.  Please explain.

**Comment by rishabh3112** [comment]
@sendilkumarn `webpack-cli` doesn't have it implemented according to me.

**Comment by sendilkumarn** [comment]
Thanks @AjayPoshak 👍

**Pull request closed without merging**
